language: julia
os:
    - osx
    - linux
julia:
    - 0.6
    - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("IntegerMask"); Pkg.test("IntegerMask"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("IntegerMask")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'cd(Pkg.dir("IntegerMask")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("IntegerMask")); include(joinpath("docs", "make.jl"))'
